services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-app
    restart: unless-stopped
    working_dir: /var/www/
    command: bash -c "php artisan scribe:generate && php-fpm"
    volumes:
      - ./:/var/www
    networks:
      - auth-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  nginx:
    image: nginx:alpine
    container_name: auth-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - auth-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: auth-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shield_auth_db
      MYSQL_USER: shield_auth_user
      MYSQL_PASSWORD: 46t#kf86T
      MYSQL_ROOT_PASSWORD: 46t#kf86T
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - auth-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:alpine
    container_name: auth-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - auth-network
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  auth-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local 